In [ ]:
import pandas as pd
from IPython.display import display, HTML
import numpy as np
import pandas as pd
from itertools import product
from PIL import Image
import os


In [ ]:
CURRENT_PATH = os.path.abspath(os.getcwd())
PARENT_DIRECTORY = os.path.dirname(CURRENT_PATH)
TFM_PATH = os.path.join(PARENT_DIRECTORY, '')
print(TFM_PATH)

In [ ]:
data = {'col1': [1,2], 'col2': [3,4]}
df = pd.DataFrame(data)
# display(HTML(df.to_html()))
print(df)

In [ ]:
def load_image_casia_multi_spectral_palmprintV1(row):
    ruta_imagen = (
        TFM_PATH
        + f"datasets/CASIA-Multi-Spectral-PalmprintV1/{row['Usuario']}_{row['Mano']}_{row['Banda']}_{row['Foto']}.jpg"
    )
    imagen = Image.open(ruta_imagen)
    imagen_array = np.array(imagen)
    return imagen_array


def load_casia_multi_spectral_palmprintV1():
    usuarios = [f"{i:03}" for i in range(1, 101)]
    manos = ["l", "r"]
    bandas = [460, 630, 700, 850, 940, "WHT"]
    fotos = [f"{i:02}" for i in range(1, 7)]
    df = pd.DataFrame(
        product(usuarios, manos, bandas, fotos),
        columns=["Usuario", "Mano", "Banda", "Foto"],
    )

    df["Imagen"] = df.apply(lambda row: load_image_casia_multi_spectral_palmprintV1(row), axis=1)
    display(df.head())


load_casia_multi_spectral_palmprintV1()

In [ ]:

def check_file_casia_palmprintV1(row):
    return os.path.exists(TFM_PATH + f"datasets/CASIA-PalmprintV1/{row['Usuario']}/{row['Usuario']}_{row['Mano']}_{row['Genero']}_{row['Foto']}.jpg"
    )
    

def load_image_casia_palmprintV1(row):
    ruta_imagen = TFM_PATH + f"datasets/CASIA-PalmprintV1/{row['Usuario']}/{row['Usuario']}_{row['Mano']}_{row['Genero']}_{row['Foto']}.jpg"
    imagen = Image.open(ruta_imagen)
    imagen_array = np.array(imagen)
    return imagen_array


def load_casia_palmprintV1():
    usuarios = [f"{i:04}" for i in range(1, 313)]
    genero = ["m", "f"]
    manos = ["l", "r"]
    fotos = [f"{i:02}" for i in range(1, 16)]
    # Crear el dataframe
    df = pd.DataFrame(
        product(usuarios, genero, manos, fotos),
        columns=["Usuario", "Mano", "Genero", "Foto"],
    )
    condition = df.apply(lambda row: check_file_casia_palmprintV1(row), axis=1)
    df = df[condition]

    df["Imagen"] = df.apply(lambda row: load_image_casia_palmprintV1(row), axis=1)
    display(df)

load_casia_palmprintV1()


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt

%matplotlib inline

img = Image.open(TFM_PATH + "datasets/CASIA-Multi-Spectral-PalmprintV1/001_l_460_01.jpg")
plt.imshow(img,cmap='jet')

In [ ]:
import torch
from torch import nn

m = nn.Bilinear(20, 30, 40)
input1 = torch.randn(128, 20)
input2 = torch.randn(128, 30)
output = m(input1, input2)
output

In [ ]:
import torch
import matplotlib.pyplot as plt
import numpy as np

# Crear un tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Convertir a NumPy
numpy_array = tensor.numpy()

# Visualizar usando Matplotlib
plt.imshow(numpy_array, cmap='viridis')
plt.colorbar()
plt.show()

In [ ]:
import matplotlib.pyplot as plt
def show_images(images) -> None:
    n: int = len(images)
    f = plt.figure()
    for i in range(n):
        # Debug, plot figure
        f.add_subplot(1, n, i + 1)
        plt.title(images[i].get('title'))
        plt.imshow(images[i].get('data'))

    plt.show(block=True)


In [ ]:
import torch
from torch import nn

m = nn.Bilinear(20, 30, 40)
input1 = torch.randn(128, 20)
input2 = torch.randn(128, 30)
output = m(input1, input2)

out_img = output.detach().numpy()
out_img_arr = np.squeeze(out_img)

show_images(
    [
        {"title": "numpy", "data": out_img},
        {"title": "squeeze", "data": out_img_arr},
    ]
)

In [ ]:
import torchshow as ts
import torch
from torch import nn

m = nn.Bilinear(20, 30, 40)
input1 = torch.randn(128, 20)
input2 = torch.randn(128, 30)
output = m(input1, input2)

ts.set_color_mode('rgb')
ts.show(output,  unnormalize='imagenet')

In [ ]:
import torch

torch.normal(mean=0, std=1, size=(32, 100))

tensor([[-0.6045, -0.1969, -0.4164,  0.4648,  1.6402, -1.0579,  1.2883,  0.2784,
          1.2851, -1.4012,  0.4316,  1.2159,  0.6169,  0.0397, -1.4821, -0.9811,
          0.3087,  0.0885, -1.1676, -0.3285,  1.0259,  0.1806, -1.7745, -1.0337,
          0.4327,  0.0385,  0.0381,  0.7570,  0.7124,  0.3359, -0.1389,  0.6530,
         -1.4402, -0.3151,  1.5652, -1.4770, -0.2590, -0.1304, -1.4664,  0.7792,
          0.8231,  0.9012,  2.0609, -1.1325, -0.5043, -0.1015, -1.6871,  0.8658,
          0.3348, -0.5540, -0.8563,  0.7274, -0.5741,  1.0043,  0.2864,  0.8648,
         -0.2774,  0.1927,  1.1961, -0.4853, -0.2031,  0.1835, -0.0254,  0.5862,
         -0.2244, -0.5164,  1.2493,  0.2654, -1.3117,  0.9570,  0.0611, -0.2807,
         -0.2448, -1.8818,  0.7124, -0.3293,  0.0945, -0.8446,  2.0068, -0.2829,
         -0.1627,  1.0961,  0.7378, -0.6666, -0.3399, -1.4812, -0.1479,  1.5296,
         -0.1147,  0.5544, -0.1046, -0.8106,  1.2409, -1.1422, -1.1766,  0.0778,
         -0.6657,  2.0609,  

In [2]:
import tensorflow as tf

tf.random.normal([32, 100])

<tf.Tensor: shape=(32, 100), dtype=float32, numpy=
array([[ 1.0425671 , -0.3946674 ,  1.9143413 , ...,  0.39238945,
         1.3988976 , -2.292512  ],
       [ 1.2902411 , -0.7941994 , -0.5041753 , ..., -0.71291786,
        -0.05493522,  0.27841508],
       [-1.0222225 , -1.9459194 , -0.61965686, ..., -1.2329023 ,
        -2.242136  ,  1.5528693 ],
       ...,
       [-0.5844678 , -0.22172196,  1.0140773 , ..., -0.21532339,
        -1.1727126 , -0.8366579 ],
       [ 0.100999  , -0.09992431,  1.3351063 , ...,  0.32248324,
        -0.6542729 ,  0.9464088 ],
       [-0.35819712,  0.8050211 , -0.55989236, ...,  0.8782153 ,
        -0.02537242, -0.49437252]], dtype=float32)>